# Generated by Django 5.2 on 2025-05-05 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='id',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='dislike',
            old_name='id',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='id',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='id',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='id',
            new_name='uuid',
        ),
    ]
