# Generated by Django 5.2 on 2025-05-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0002_user_subscribers_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('1', 'Personal life'), ('2', 'Traveling'), ('3', 'Education'), ('4', 'Career'), ('5', 'Psychology'), ('6', 'Health'), ('7', 'Hobbys'), ('8', 'Art'), ('9', 'Music'), ('10', 'Films'), ('11', 'Books'), ('12', 'Technology'), ('13', 'Science'), ('14', 'Sport'), ('15', 'Cooking'), ('16', 'Policy'), ('17', 'Philosophy'), ('18', 'Self-Development'), ('19', 'Motivation'), ('20', 'Social')], default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='subscribers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
