# Generated by Django 5.2 on 2025-05-04 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0003_post_category_alter_user_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('personal_life', 'Personal life'), ('traveling', 'Traveling'), ('education', 'Education'), ('career', 'Career'), ('psychology', 'Psychology'), ('health', 'Health'), ('hobbys', 'Hobbys'), ('art', 'Art'), ('music', 'Music'), ('films', 'Films'), ('books', 'Books'), ('technology', 'Technology'), ('science', 'Science'), ('sport', 'Sport'), ('cooking', 'Cooking'), ('policy', 'Policy'), ('philosophy', 'Philosophy'), ('self_development', 'Self-development'), ('motivation', 'Motivation'), ('social', 'Social')], max_length=255),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diaries.post')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
